### ISSUE TITLE
precip.today intermittent nonsensical

### ISSUE THREAD

**Issue by tbuckler** [DaveL17/WUnderground#6]
Every now and then when there is a precipitation event, the value for precip.today jumps from the correct value to -99. Not sure what to do about debugging this. Using plugin 6.0.07 with Indigo 6.1.11.

**Comment by DaveL17** [comment]
Many of us are experiencing issues with the Weather Underground API and the plugin seems to be working as intended.  When this event happens, the plugin is receiving the -99 (which is an indication that WU don't know what the valid value is) or is receiving something it can't convert to a rational value. It wouldn't be right to trap the -99 and change it to something else (like zero) because the rational value may be non-zero.  

The recommended approach if you are using the plugin to display weather data only is to be patient and hope for a fix from WU. If you're using the data for any critical automation, the recommendation is to add appropriate safeguards using Indigo.  For example, create a variable, store the precip value in the variable and increment it only when the new plugin value is greater than the old variable value (resetting at the frequency of choice).

Cheers and thanks for reporting the potential bug.

**Comment by tbuckler** [comment]
Thanks!


Tom Buckler | Buckler Microelectronics Inc.
17008 - 90 Avenue NW | Suite 272 | Edmonton | AB | Canada | T5T 1L6
Cell: (780) 499-5525
